-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 16:23:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Construempleo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Construempleo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Construempleo` ;
USE `Construempleo` ;

-- -----------------------------------------------------
-- Table `Construempleo`.`tipo_ID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`tipo_ID` (
  `id_tipo_ID` INT NOT NULL AUTO_INCREMENT,
  `nom_tipo_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_ID`),
  UNIQUE INDEX `id_TipoID_UNIQUE` (`id_tipo_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nom_genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `id_genero_UNIQUE` (`id_genero` ASC) VISIBLE,
  UNIQUE INDEX `nombre_genero_UNIQUE` (`nom_genero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`eps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`eps` (
  `id_eps` INT NOT NULL AUTO_INCREMENT,
  `nom_eps` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_eps`),
  UNIQUE INDEX `id_eps_UNIQUE` (`id_eps` ASC) VISIBLE,
  UNIQUE INDEX `nombre_eps_UNIQUE` (`nom_eps` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`profesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`profesion` (
  `id_profesion` INT NOT NULL AUTO_INCREMENT,
  `nom_profesion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profesion`),
  UNIQUE INDEX `id_profesion_UNIQUE` (`id_profesion` ASC) VISIBLE,
  UNIQUE INDEX `nombre_profesion_UNIQUE` (`nom_profesion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`depto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`depto` (
  `id_depto` INT NOT NULL AUTO_INCREMENT,
  `nom_depto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_depto`),
  UNIQUE INDEX `id_depto_UNIQUE` (`id_depto` ASC) VISIBLE,
  UNIQUE INDEX `nom_depto_UNIQUE` (`nom_depto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`ciudad_nac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`ciudad_nac` (
  `id_ciudad_nac` INT NOT NULL AUTO_INCREMENT,
  `nom_ciudad_nac` VARCHAR(45) NOT NULL,
  `depto_id_depto` INT NOT NULL,
  PRIMARY KEY (`id_ciudad_nac`),
  UNIQUE INDEX `idciudad_residencia_UNIQUE` (`id_ciudad_nac` ASC) VISIBLE,
  UNIQUE INDEX `nombre_ciudad_residencia_UNIQUE` (`nom_ciudad_nac` ASC) VISIBLE,
  INDEX `fk_ciudad_nac_depto1_idx` (`depto_id_depto` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_nac_depto1`
    FOREIGN KEY (`depto_id_depto`)
    REFERENCES `Construempleo`.`depto` (`id_depto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nom_tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `id_tipo_usuario_UNIQUE` (`id_tipo_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nombre_tipo_usuario_UNIQUE` (`nom_tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`ciudad_res`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`ciudad_res` (
  `id_ciudad_res` INT NOT NULL AUTO_INCREMENT,
  `nom_ciudad_res` VARCHAR(45) NOT NULL,
  `depto_id_depto` INT NOT NULL,
  PRIMARY KEY (`id_ciudad_res`),
  UNIQUE INDEX `idciudad_residencia_UNIQUE` (`id_ciudad_res` ASC) VISIBLE,
  UNIQUE INDEX `nombre_ciudad_residencia_UNIQUE` (`nom_ciudad_res` ASC) VISIBLE,
  INDEX `fk_ciudad_res_depto1_idx` (`depto_id_depto` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_res_depto1`
    FOREIGN KEY (`depto_id_depto`)
    REFERENCES `Construempleo`.`depto` (`id_depto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`candidato` (
  `id_candidato` INT NOT NULL,
  `nombre1_candidato` VARCHAR(45) NOT NULL,
  `nombre2_candidato` VARCHAR(45) NULL,
  `ape1_candidato` VARCHAR(45) NOT NULL,
  `ape2_candidato` VARCHAR(45) NULL,
  `nac_candidato` DATE NOT NULL,
  `dir_candidato` VARCHAR(45) NOT NULL,
  `tel_candidato` INT NULL,
  `celr_candidato` INT NOT NULL,
  `exp_candidato` DATE NOT NULL,
  `email_candidato` VARCHAR(45) NOT NULL,
  `user_candidato` VARCHAR(45) NOT NULL,
  `password_candidato` VARCHAR(45) NOT NULL,
  `tipo_ID_id_tipo_ID` INT NOT NULL,
  `genero_id_genero` INT NOT NULL,
  `eps_id_eps` INT NOT NULL,
  `profesion_id_profesion` INT NOT NULL,
  `ciudad_nac_id_ciudad_nac` INT NOT NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  `ciudad_res_id_ciudad_res` INT NOT NULL,
  PRIMARY KEY (`id_candidato`),
  UNIQUE INDEX `id_candidato_UNIQUE` (`id_candidato` ASC) VISIBLE,
  UNIQUE INDEX `celular_candidato_UNIQUE` (`celr_candidato` ASC) VISIBLE,
  UNIQUE INDEX `email_candidato_UNIQUE` (`email_candidato` ASC) VISIBLE,
  UNIQUE INDEX `user_candidato_UNIQUE` (`user_candidato` ASC) VISIBLE,
  UNIQUE INDEX `password_candidato_UNIQUE` (`password_candidato` ASC) VISIBLE,
  INDEX `fk_candidato_tipo_ID_idx` (`tipo_ID_id_tipo_ID` ASC) VISIBLE,
  INDEX `fk_candidato_genero1_idx` (`genero_id_genero` ASC) VISIBLE,
  INDEX `fk_candidato_eps1_idx` (`eps_id_eps` ASC) VISIBLE,
  INDEX `fk_candidato_profesion1_idx` (`profesion_id_profesion` ASC) VISIBLE,
  INDEX `fk_candidato_ciudad_nac1_idx` (`ciudad_nac_id_ciudad_nac` ASC) VISIBLE,
  INDEX `fk_candidato_tipo_usuario1_idx` (`tipo_usuario_id_tipo_usuario` ASC) VISIBLE,
  INDEX `fk_candidato_ciudad_res1_idx` (`ciudad_res_id_ciudad_res` ASC) VISIBLE,
  CONSTRAINT `fk_candidato_tipo_ID`
    FOREIGN KEY (`tipo_ID_id_tipo_ID`)
    REFERENCES `Construempleo`.`tipo_ID` (`id_tipo_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_genero1`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `Construempleo`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_eps1`
    FOREIGN KEY (`eps_id_eps`)
    REFERENCES `Construempleo`.`eps` (`id_eps`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_profesion1`
    FOREIGN KEY (`profesion_id_profesion`)
    REFERENCES `Construempleo`.`profesion` (`id_profesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_ciudad_nac1`
    FOREIGN KEY (`ciudad_nac_id_ciudad_nac`)
    REFERENCES `Construempleo`.`ciudad_nac` (`id_ciudad_nac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `Construempleo`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_ciudad_res1`
    FOREIGN KEY (`ciudad_res_id_ciudad_res`)
    REFERENCES `Construempleo`.`ciudad_res` (`id_ciudad_res`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`estado_educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`estado_educacion` (
  `id_estado_educacion` INT NOT NULL AUTO_INCREMENT,
  `nom_estado_educacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_educacion`),
  UNIQUE INDEX `id_estado_educacion_UNIQUE` (`id_estado_educacion` ASC) VISIBLE,
  UNIQUE INDEX `nombre_estado_educacion_UNIQUE` (`nom_estado_educacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`nivel_educativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`nivel_educativo` (
  `id_nivel_educativo` INT NOT NULL AUTO_INCREMENT,
  `nom_nivel_educativo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_nivel_educativo`),
  UNIQUE INDEX `id_nivel_educativo_UNIQUE` (`id_nivel_educativo` ASC) VISIBLE,
  UNIQUE INDEX `nivel_educativocol_UNIQUE` (`nom_nivel_educativo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`ciudad_edu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`ciudad_edu` (
  `id_ciudad_edu` INT NOT NULL AUTO_INCREMENT,
  `nom_ciudad_edu` VARCHAR(45) NOT NULL,
  `depto_id_depto` INT NOT NULL,
  PRIMARY KEY (`id_ciudad_edu`),
  UNIQUE INDEX `idciudad_residencia_UNIQUE` (`id_ciudad_edu` ASC) VISIBLE,
  UNIQUE INDEX `nombre_ciudad_residencia_UNIQUE` (`nom_ciudad_edu` ASC) VISIBLE,
  INDEX `fk_ciudad_edu_depto1_idx` (`depto_id_depto` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_edu_depto1`
    FOREIGN KEY (`depto_id_depto`)
    REFERENCES `Construempleo`.`depto` (`id_depto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`educacion` (
  `id_educacion` INT NOT NULL AUTO_INCREMENT,
  `nom_educacion` VARCHAR(45) NOT NULL,
  `tit_educacion` VARCHAR(45) NOT NULL,
  `fechagra_educacion` DATE NULL,
  `estado_educacion_id_estado_educacion` INT NOT NULL,
  `nivel_educativo_id_nivel_educativo` INT NOT NULL,
  `candidato_id_candidato` INT NOT NULL,
  `ciudad_edu_id_ciudad_edu` INT NOT NULL,
  PRIMARY KEY (`id_educacion`),
  UNIQUE INDEX `id_educacion_UNIQUE` (`id_educacion` ASC) VISIBLE,
  INDEX `fk_educacion_estado_educacion1_idx` (`estado_educacion_id_estado_educacion` ASC) VISIBLE,
  INDEX `fk_educacion_nivel_educativo1_idx` (`nivel_educativo_id_nivel_educativo` ASC) VISIBLE,
  INDEX `fk_educacion_candidato1_idx` (`candidato_id_candidato` ASC) VISIBLE,
  INDEX `fk_educacion_ciudad_edu1_idx` (`ciudad_edu_id_ciudad_edu` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_estado_educacion1`
    FOREIGN KEY (`estado_educacion_id_estado_educacion`)
    REFERENCES `Construempleo`.`estado_educacion` (`id_estado_educacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educacion_nivel_educativo1`
    FOREIGN KEY (`nivel_educativo_id_nivel_educativo`)
    REFERENCES `Construempleo`.`nivel_educativo` (`id_nivel_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educacion_candidato1`
    FOREIGN KEY (`candidato_id_candidato`)
    REFERENCES `Construempleo`.`candidato` (`id_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educacion_ciudad_edu1`
    FOREIGN KEY (`ciudad_edu_id_ciudad_edu`)
    REFERENCES `Construempleo`.`ciudad_edu` (`id_ciudad_edu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`ciudad_empl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`ciudad_empl` (
  `id_ciudad_empl` INT NOT NULL AUTO_INCREMENT,
  `nom_ciudad_empl` VARCHAR(45) NOT NULL,
  `depto_id_depto` INT NOT NULL,
  PRIMARY KEY (`id_ciudad_empl`),
  UNIQUE INDEX `idciudad_residencia_UNIQUE` (`id_ciudad_empl` ASC) VISIBLE,
  UNIQUE INDEX `nombre_ciudad_residencia_UNIQUE` (`nom_ciudad_empl` ASC) VISIBLE,
  INDEX `fk_ciudad_empl_depto1_idx` (`depto_id_depto` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_empl_depto1`
    FOREIGN KEY (`depto_id_depto`)
    REFERENCES `Construempleo`.`depto` (`id_depto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`empleador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`empleador` (
  `id_empleador` INT NOT NULL,
  `nom_empleador` VARCHAR(45) NOT NULL,
  `ape_empleador` VARCHAR(45) NOT NULL,
  `raz_empleador` VARCHAR(45) NULL,
  `tel_empleador` INT NOT NULL,
  `cel_empleador` VARCHAR(45) NOT NULL,
  `direccion_empleador` VARCHAR(45) NOT NULL,
  `email_empleador` VARCHAR(45) NOT NULL,
  `user_empleador` VARCHAR(45) NOT NULL,
  `pass_empleador` VARCHAR(45) NOT NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  `ciudad_empl_id_ciudad_empl` INT NOT NULL,
  `tipo_ID_id_tipo_ID` INT NOT NULL,
  PRIMARY KEY (`id_empleador`),
  UNIQUE INDEX `id_empleador_UNIQUE` (`id_empleador` ASC) VISIBLE,
  UNIQUE INDEX `nombre_empleador_UNIQUE` (`nom_empleador` ASC) VISIBLE,
  UNIQUE INDEX `telefono_empleador_UNIQUE` (`tel_empleador` ASC) VISIBLE,
  UNIQUE INDEX `celular_empleador_UNIQUE` (`cel_empleador` ASC) VISIBLE,
  UNIQUE INDEX `email_empleador_UNIQUE` (`email_empleador` ASC) VISIBLE,
  UNIQUE INDEX `direccion_empleador_UNIQUE` (`direccion_empleador` ASC) VISIBLE,
  UNIQUE INDEX `user_empleador_UNIQUE` (`user_empleador` ASC) VISIBLE,
  INDEX `fk_empleador_tipo_usuario1_idx` (`tipo_usuario_id_tipo_usuario` ASC) VISIBLE,
  INDEX `fk_empleador_ciudad_empl1_idx` (`ciudad_empl_id_ciudad_empl` ASC) VISIBLE,
  INDEX `fk_empleador_tipo_ID1_idx` (`tipo_ID_id_tipo_ID` ASC) VISIBLE,
  UNIQUE INDEX `ape_empleador_UNIQUE` (`ape_empleador` ASC) VISIBLE,
  UNIQUE INDEX `raz_empleador_UNIQUE` (`raz_empleador` ASC) VISIBLE,
  CONSTRAINT `fk_empleador_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `Construempleo`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleador_ciudad_empl1`
    FOREIGN KEY (`ciudad_empl_id_ciudad_empl`)
    REFERENCES `Construempleo`.`ciudad_empl` (`id_ciudad_empl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleador_tipo_ID1`
    FOREIGN KEY (`tipo_ID_id_tipo_ID`)
    REFERENCES `Construempleo`.`tipo_ID` (`id_tipo_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`Vacante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`Vacante` (
  `id_vacante` INT NOT NULL AUTO_INCREMENT,
  `tit_vacante` VARCHAR(45) NOT NULL,
  `desc_vacante` VARCHAR(45) NOT NULL,
  `fechapub_vacante` DATE NOT NULL,
  `fechavenc_vacante` DATE NOT NULL,
  `empleador_id_empleador` INT NOT NULL,
  `profesion_id_profesion` INT NOT NULL,
  PRIMARY KEY (`id_vacante`),
  UNIQUE INDEX `id_vacante_UNIQUE` (`id_vacante` ASC) VISIBLE,
  INDEX `fk_Vacante_empleador1_idx` (`empleador_id_empleador` ASC) VISIBLE,
  INDEX `fk_Vacante_profesion1_idx` (`profesion_id_profesion` ASC) VISIBLE,
  CONSTRAINT `fk_Vacante_empleador1`
    FOREIGN KEY (`empleador_id_empleador`)
    REFERENCES `Construempleo`.`empleador` (`id_empleador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacante_profesion1`
    FOREIGN KEY (`profesion_id_profesion`)
    REFERENCES `Construempleo`.`profesion` (`id_profesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`ciudad_exp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`ciudad_exp` (
  `id_ciudad_exp` INT NOT NULL AUTO_INCREMENT,
  `nom_ciudad_exp` VARCHAR(45) NOT NULL,
  `depto_id_depto` INT NOT NULL,
  PRIMARY KEY (`id_ciudad_exp`),
  UNIQUE INDEX `idciudad_residencia_UNIQUE` (`id_ciudad_exp` ASC) VISIBLE,
  UNIQUE INDEX `nombre_ciudad_residencia_UNIQUE` (`nom_ciudad_exp` ASC) VISIBLE,
  INDEX `fk_ciudad_exp_depto1_idx` (`depto_id_depto` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_exp_depto1`
    FOREIGN KEY (`depto_id_depto`)
    REFERENCES `Construempleo`.`depto` (`id_depto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`experiencia` (
  `id_experiencia` INT NOT NULL AUTO_INCREMENT,
  `empresa_experiencia` VARCHAR(45) NOT NULL,
  `cargo_experiencia` VARCHAR(45) NOT NULL,
  `func_experiencia` VARCHAR(45) NOT NULL,
  `fechaing_experiencia` VARCHAR(45) NOT NULL,
  `fechasal_experiencia` VARCHAR(45) NULL,
  `dir_experiencia` VARCHAR(45) NOT NULL,
  `cel_experiencia` VARCHAR(45) NOT NULL,
  `tel_experiencia` INT NOT NULL,
  `jefe_experiencia` VARCHAR(45) NOT NULL,
  `candidato_id_candidato` INT NOT NULL,
  `ciudad_exp_id_ciudad_exp` INT NOT NULL,
  PRIMARY KEY (`id_experiencia`),
  UNIQUE INDEX `id_experiencia_UNIQUE` (`id_experiencia` ASC) VISIBLE,
  UNIQUE INDEX `direccion_experiencia_UNIQUE` (`dir_experiencia` ASC) VISIBLE,
  INDEX `fk_experiencia_candidato1_idx` (`candidato_id_candidato` ASC) VISIBLE,
  INDEX `fk_experiencia_ciudad_exp1_idx` (`ciudad_exp_id_ciudad_exp` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_candidato1`
    FOREIGN KEY (`candidato_id_candidato`)
    REFERENCES `Construempleo`.`candidato` (`id_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_ciudad_exp1`
    FOREIGN KEY (`ciudad_exp_id_ciudad_exp`)
    REFERENCES `Construempleo`.`ciudad_exp` (`id_ciudad_exp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Construempleo`.`postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Construempleo`.`postulacion` (
  `id_postulacion` INT NOT NULL AUTO_INCREMENT,
  `vencimiento_publ` VARCHAR(45) NOT NULL,
  `fecha_post` DATETIME NOT NULL,
  `candidato_id_candidato` INT NOT NULL,
  `Vacante_id_vacante` INT NOT NULL,
  PRIMARY KEY (`id_postulacion`),
  UNIQUE INDEX `id_postulacion_UNIQUE` (`id_postulacion` ASC) VISIBLE,
  UNIQUE INDEX `fecha_postulacion_UNIQUE` (`fecha_post` ASC) VISIBLE,
  UNIQUE INDEX `vencimiento_publicacion_UNIQUE` (`vencimiento_publ` ASC) VISIBLE,
  INDEX `fk_postulacion_candidato1_idx` (`candidato_id_candidato` ASC) VISIBLE,
  INDEX `fk_postulacion_Vacante1_idx` (`Vacante_id_vacante` ASC) VISIBLE,
  CONSTRAINT `fk_postulacion_candidato1`
    FOREIGN KEY (`candidato_id_candidato`)
    REFERENCES `Construempleo`.`candidato` (`id_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulacion_Vacante1`
    FOREIGN KEY (`Vacante_id_vacante`)
    REFERENCES `Construempleo`.`Vacante` (`id_vacante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY 'admin';

GRANT ALL ON `Construempleo`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
